<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dealer.proto

namespace GPBMetadata;

class Dealer
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Shopex::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac9020a0c6465616c65722e70726f746f12056c7562616e22230a105472" .
            "616465496e666f52657175657374120f0a075472616465426e1801200128" .
            "09223f0a1154726164654c697374526573706f6e7365121b0a0554726164" .
            "6518012003280b320c2e6c7562616e2e5472616465120d0a05436f756e74" .
            "180220012803329d010a064465616c657212220a044465616c120c2e6c75" .
            "62616e2e54726164651a0c2e6c7562616e2e547261646512320a09547261" .
            "6465496e666f12172e6c7562616e2e5472616465496e666f526571756573" .
            "741a0c2e6c7562616e2e5472616465123b0a0954726164654c6973741214" .
            "2e6c7562616e2e536561726368526571756573741a182e6c7562616e2e54" .
            "726164654c697374526573706f6e736542240a0f636e2e73686f7065782e" .
            "6c7562616eca021053686f7065785c4c7562616e5c536466620670726f74" .
            "6f33"
        ));

        static::$is_initialized = true;
    }
}

