<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dealer.proto

namespace GPBMetadata;

class Dealer
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Shopex::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad1020a0c6465616c65722e70726f746f12056c7562616e22230a105472" .
            "616465496e666f52657175657374120f0a07547261646549641801200128" .
            "0922120a1054726164654c6973745265717565737422300a115472616465" .
            "4c697374526573706f6e7365121b0a05547261646518012001280b320c2e" .
            "6c7562616e2e547261646532a0010a064465616c657212220a044465616c" .
            "120c2e6c7562616e2e54726164651a0c2e6c7562616e2e54726164651232" .
            "0a095472616465496e666f12172e6c7562616e2e5472616465496e666f52" .
            "6571756573741a0c2e6c7562616e2e5472616465123e0a0954726164654c" .
            "69737412172e6c7562616e2e54726164654c697374526571756573741a18" .
            "2e6c7562616e2e54726164654c697374526573706f6e736542240a0f636e" .
            "2e73686f7065782e6c7562616eca021053686f7065785c4c7562616e5c53" .
            "6466620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

