<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment.proto

namespace GPBMetadata;

class Payment
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Support::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0abd020a0d7061796d656e742e70726f746f12056c7562616e22f6010a07" .
            "5061796d656e7412110a095061796d656e744964180120012809120b0a03" .
            "546964180220012809120e0a06416d6f756e74180320012801120e0a064d" .
            "6574686f64180420012809120f0a074368616e6e656c180520012809120f" .
            "0a075472616e73496418062001280912100a085061696454696d65180820" .
            "01280312290a0653746174757318092001280e32192e6c7562616e2e5061" .
            "796d656e742e456e756d53746174757312190a044d657461180a2003280b" .
            "320b2e6c7562616e2e4d65746122310a0a456e756d53746174757312120a" .
            "0e574149545f42555945525f5041591000120f0a0b5041595f5355434345" .
            "5353100142240a0f636e2e73686f7065782e6c7562616eca021053686f70" .
            "65785c4c7562616e5c536466620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

