<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment.proto

namespace GPBMetadata;

class Payment
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Support::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aab020a0d7061796d656e742e70726f746f12056c7562616e22e4010a07" .
            "5061796d656e7412110a095061796d656e744964180120012809120b0a03" .
            "546964180220012809120e0a06416d6f756e74180320012801120e0a064d" .
            "6574686f64180420012809120f0a074368616e6e656c180520012809120f" .
            "0a075472616e73496418062001280912290a065374617475731807200128" .
            "0e32192e6c7562616e2e5061796d656e742e456e756d5374617475731219" .
            "0a044d65746118082003280b320b2e6c7562616e2e4d65746122310a0a45" .
            "6e756d53746174757312120a0e574149545f42555945525f504159100012" .
            "0f0a0b5041595f53554343455353100142240a0f636e2e73686f7065782e" .
            "6c7562616eca021053686f7065785c4c7562616e5c536466620670726f74" .
            "6f33"
        ));

        static::$is_initialized = true;
    }
}

