<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shipment.proto

namespace GPBMetadata;

class Shipment
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Support::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aaf020a0e736869706d656e742e70726f746f12056c7562616e22a9010a" .
            "08536869706d656e74120b0a0354696418012001280912150a0d4c6f6769" .
            "7374696373436f646518022001280912150a0d4c6f676973746963734e61" .
            "6d6518032001280912130a0b547261636b4e756d62657218042001280912" .
            "120a0a43726561746554696d65180520012803121e0a054974656d731808" .
            "2003280b320f2e6c7562616e2e536869704974656d12190a044d65746118" .
            "0a2003280b320b2e6c7562616e2e4d657461223c0a08536869704974656d" .
            "120d0a05536b75496418012001280912100a085175616e74697479180220" .
            "012803120f0a074f72646572496418032001280942240a0f636e2e73686f" .
            "7065782e6c7562616eca021053686f7065785c4c7562616e5c5364666206" .
            "70726f746f33"
        ));

        static::$is_initialized = true;
    }
}

