<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shipment.proto

namespace GPBMetadata;

class Shipment
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Support::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aff010a0e736869706d656e742e70726f746f12056c7562616e22b7010a" .
            "08536869706d656e74120b0a03546964180120012809120f0a0743617272" .
            "69657218022001280912130a0b547261636b4e756d626572180320012809" .
            "122a0a0653746174757318042001280e321a2e6c7562616e2e536869706d" .
            "656e742e456e756d53746174757312190a044d65746118052003280b320b" .
            "2e6c7562616e2e4d65746122310a0a456e756d53746174757312120a0e57" .
            "4149545f42555945525f5041591000120f0a0b5041595f53554343455353" .
            "100142240a0f636e2e73686f7065782e6c7562616eca021053686f706578" .
            "5c4c7562616e5c536466620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

