<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shipment.proto

namespace GPBMetadata;

class Shipment
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Support::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a92020a0e736869706d656e742e70726f746f12056c7562616e228c010a" .
            "08536869706d656e74120b0a03546964180120012809120f0a0743617272" .
            "69657218022001280912130a0b547261636b4e756d626572180320012809" .
            "12120a0a43726561746554696d65180720012803121e0a054974656d7318" .
            "082003280b320f2e6c7562616e2e536869704974656d12190a044d657461" .
            "180a2003280b320b2e6c7562616e2e4d657461223c0a0853686970497465" .
            "6d120d0a05536b75496418012001280912100a085175616e746974791802" .
            "20012803120f0a074f72646572496418032001280942240a0f636e2e7368" .
            "6f7065782e6c7562616eca021053686f7065785c4c7562616e5c53646662" .
            "0670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

