<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trigger.proto

namespace GPBMetadata;

class Trigger
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0afb020a0d747269676765722e70726f746f12056c7562616e22b4020a07" .
            "54726967676572120d0a054576656e7418012001280912250a044d6f6465" .
            "18022001280e32172e6c7562616e2e547269676765722e4d6f6465547970" .
            "65120f0a0746696c7465727318032001280912110a0946696c7465724c75" .
            "61180420012809120f0a07416374696f6e7318052001280912110a094265" .
            "67696e54696d65180620012803120f0a07456e6454696d65180720012803" .
            "120e0a0653697465496418082001280312110a094f72646572536f727418" .
            "092001280312130a0b4465736372697074696f6e180a2001280912230a06" .
            "49734c6f636b180b2001280e32132e6c7562616e2e547269676765722e4c" .
            "6f636b221c0a044c6f636b120a0a06554e4c4f434b100012080a044c4f43" .
            "4b1001221f0a084d6f646554797065120a0a064e4f524d414c100012070a" .
            "034c5541100142240a0f636e2e73686f7065782e6c7562616eca02105368" .
            "6f7065785c4c7562616e5c536466620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

