<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shopex.proto

namespace Shopex\Luban\Sdf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>luban.Address</code>
 */
class Address extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Name = 2;</code>
     */
    private $Name = '';
    /**
     * Generated from protobuf field <code>string Phone = 4;</code>
     */
    private $Phone = '';
    /**
     * Generated from protobuf field <code>.luban.Location Location = 3;</code>
     */
    private $Location = null;
    /**
     * Generated from protobuf field <code>string Address1 = 5;</code>
     */
    private $Address1 = '';
    /**
     * Generated from protobuf field <code>string Address2 = 6;</code>
     */
    private $Address2 = '';

    public function __construct() {
        \GPBMetadata\Shopex::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string Name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->Name;
    }

    /**
     * Generated from protobuf field <code>string Name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->Name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Phone = 4;</code>
     * @return string
     */
    public function getPhone()
    {
        return $this->Phone;
    }

    /**
     * Generated from protobuf field <code>string Phone = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->Phone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.luban.Location Location = 3;</code>
     * @return \Shopex\Luban\Sdf\Location
     */
    public function getLocation()
    {
        return $this->Location;
    }

    /**
     * Generated from protobuf field <code>.luban.Location Location = 3;</code>
     * @param \Shopex\Luban\Sdf\Location $var
     * @return $this
     */
    public function setLocation($var)
    {
        GPBUtil::checkMessage($var, \Shopex\Luban\Sdf\Location::class);
        $this->Location = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Address1 = 5;</code>
     * @return string
     */
    public function getAddress1()
    {
        return $this->Address1;
    }

    /**
     * Generated from protobuf field <code>string Address1 = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress1($var)
    {
        GPBUtil::checkString($var, True);
        $this->Address1 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Address2 = 6;</code>
     * @return string
     */
    public function getAddress2()
    {
        return $this->Address2;
    }

    /**
     * Generated from protobuf field <code>string Address2 = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress2($var)
    {
        GPBUtil::checkString($var, True);
        $this->Address2 = $var;

        return $this;
    }

}

