<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: support.proto

namespace Shopex\Luban\Sdf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>luban.Address</code>
 */
class Address extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Name = 1;</code>
     */
    private $Name = '';
    /**
     * Generated from protobuf field <code>string Phone = 2;</code>
     */
    private $Phone = '';
    /**
     * Generated from protobuf field <code>.luban.Gender Gender = 3;</code>
     */
    private $Gender = 0;
    /**
     *省份
     *
     * Generated from protobuf field <code>string Province = 4;</code>
     */
    private $Province = '';
    /**
     *市
     *
     * Generated from protobuf field <code>string City = 5;</code>
     */
    private $City = '';
    /**
     *区
     *
     * Generated from protobuf field <code>string District = 6;</code>
     */
    private $District = '';
    /**
     *街道
     *
     * Generated from protobuf field <code>string SubDistrict = 7;</code>
     */
    private $SubDistrict = '';
    /**
     * Generated from protobuf field <code>string Zip = 8;</code>
     */
    private $Zip = '';
    /**
     * Generated from protobuf field <code>string Address1 = 9;</code>
     */
    private $Address1 = '';
    /**
     * Generated from protobuf field <code>string Address2 = 10;</code>
     */
    private $Address2 = '';

    public function __construct() {
        \GPBMetadata\Support::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string Name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->Name;
    }

    /**
     * Generated from protobuf field <code>string Name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->Name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Phone = 2;</code>
     * @return string
     */
    public function getPhone()
    {
        return $this->Phone;
    }

    /**
     * Generated from protobuf field <code>string Phone = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->Phone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.luban.Gender Gender = 3;</code>
     * @return int
     */
    public function getGender()
    {
        return $this->Gender;
    }

    /**
     * Generated from protobuf field <code>.luban.Gender Gender = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setGender($var)
    {
        GPBUtil::checkEnum($var, \Shopex\Luban\Sdf\Gender::class);
        $this->Gender = $var;

        return $this;
    }

    /**
     *省份
     *
     * Generated from protobuf field <code>string Province = 4;</code>
     * @return string
     */
    public function getProvince()
    {
        return $this->Province;
    }

    /**
     *省份
     *
     * Generated from protobuf field <code>string Province = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setProvince($var)
    {
        GPBUtil::checkString($var, True);
        $this->Province = $var;

        return $this;
    }

    /**
     *市
     *
     * Generated from protobuf field <code>string City = 5;</code>
     * @return string
     */
    public function getCity()
    {
        return $this->City;
    }

    /**
     *市
     *
     * Generated from protobuf field <code>string City = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->City = $var;

        return $this;
    }

    /**
     *区
     *
     * Generated from protobuf field <code>string District = 6;</code>
     * @return string
     */
    public function getDistrict()
    {
        return $this->District;
    }

    /**
     *区
     *
     * Generated from protobuf field <code>string District = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDistrict($var)
    {
        GPBUtil::checkString($var, True);
        $this->District = $var;

        return $this;
    }

    /**
     *街道
     *
     * Generated from protobuf field <code>string SubDistrict = 7;</code>
     * @return string
     */
    public function getSubDistrict()
    {
        return $this->SubDistrict;
    }

    /**
     *街道
     *
     * Generated from protobuf field <code>string SubDistrict = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setSubDistrict($var)
    {
        GPBUtil::checkString($var, True);
        $this->SubDistrict = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Zip = 8;</code>
     * @return string
     */
    public function getZip()
    {
        return $this->Zip;
    }

    /**
     * Generated from protobuf field <code>string Zip = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setZip($var)
    {
        GPBUtil::checkString($var, True);
        $this->Zip = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Address1 = 9;</code>
     * @return string
     */
    public function getAddress1()
    {
        return $this->Address1;
    }

    /**
     * Generated from protobuf field <code>string Address1 = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress1($var)
    {
        GPBUtil::checkString($var, True);
        $this->Address1 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Address2 = 10;</code>
     * @return string
     */
    public function getAddress2()
    {
        return $this->Address2;
    }

    /**
     * Generated from protobuf field <code>string Address2 = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress2($var)
    {
        GPBUtil::checkString($var, True);
        $this->Address2 = $var;

        return $this;
    }

}

