<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: svc_dealer.proto

namespace Shopex\Luban\Sdf;

/**
 * Protobuf enum <code>Luban\AfterSaleStatus</code>
 */
class AfterSaleStatus
{
    /**
     * 未处理
     *
     * Generated from protobuf enum <code>PROCESS = 0;</code>
     */
    const PROCESS = 0;
    /**
     * 处理完成
     *
     * Generated from protobuf enum <code>FINISHED = 1;</code>
     */
    const FINISHED = 1;
    /**
     * 已拒绝
     *
     * Generated from protobuf enum <code>REFUSED = 2;</code>
     */
    const REFUSED = 2;
}

