<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: svc_dealer.proto

namespace Shopex\Luban\Sdf;

/**
 * Protobuf enum <code>Luban\AfterSaleStatus</code>
 */
class AfterSaleStatus
{
    /**
     * 审核中
     *
     * Generated from protobuf enum <code>CHECKING = 0;</code>
     */
    const CHECKING = 0;
    /**
     * 处理中
     *
     * Generated from protobuf enum <code>PROCESS = 1;</code>
     */
    const PROCESS = 1;
    /**
     * 处理完成
     *
     * Generated from protobuf enum <code>FINISHED = 2;</code>
     */
    const FINISHED = 2;
    /**
     * 已拒绝
     *
     * Generated from protobuf enum <code>REFUSED = 3;</code>
     */
    const REFUSED = 3;
    /**
     * 已收货
     *
     * Generated from protobuf enum <code>RETURNED = 4;</code>
     */
    const RETURNED = 4;
}

