<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade.proto

namespace Shopex\Luban\Sdf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>luban.Event</code>
 */
class Event extends \Google\Protobuf\Internal\Message
{
    /**
     * 时间
     *
     * Generated from protobuf field <code>int64 EventTime = 1;</code>
     */
    private $EventTime = 0;
    /**
     * 操作点， 平台， 应用
     *
     * Generated from protobuf field <code>string Place = 2;</code>
     */
    private $Place = '';
    /**
     * 操作人
     *
     * Generated from protobuf field <code>string Operator = 3;</code>
     */
    private $Operator = '';
    /**
     * 代码
     *
     * Generated from protobuf field <code>string Code = 4;</code>
     */
    private $Code = '';
    /**
     * json
     *
     * Generated from protobuf field <code>string Data = 5;</code>
     */
    private $Data = '';
    /**
     * 给人看
     *
     * Generated from protobuf field <code>string Detail = 6;</code>
     */
    private $Detail = '';

    public function __construct() {
        \GPBMetadata\Trade::initOnce();
        parent::__construct();
    }

    /**
     * 时间
     *
     * Generated from protobuf field <code>int64 EventTime = 1;</code>
     * @return int|string
     */
    public function getEventTime()
    {
        return $this->EventTime;
    }

    /**
     * 时间
     *
     * Generated from protobuf field <code>int64 EventTime = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEventTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->EventTime = $var;

        return $this;
    }

    /**
     * 操作点， 平台， 应用
     *
     * Generated from protobuf field <code>string Place = 2;</code>
     * @return string
     */
    public function getPlace()
    {
        return $this->Place;
    }

    /**
     * 操作点， 平台， 应用
     *
     * Generated from protobuf field <code>string Place = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPlace($var)
    {
        GPBUtil::checkString($var, True);
        $this->Place = $var;

        return $this;
    }

    /**
     * 操作人
     *
     * Generated from protobuf field <code>string Operator = 3;</code>
     * @return string
     */
    public function getOperator()
    {
        return $this->Operator;
    }

    /**
     * 操作人
     *
     * Generated from protobuf field <code>string Operator = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setOperator($var)
    {
        GPBUtil::checkString($var, True);
        $this->Operator = $var;

        return $this;
    }

    /**
     * 代码
     *
     * Generated from protobuf field <code>string Code = 4;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->Code;
    }

    /**
     * 代码
     *
     * Generated from protobuf field <code>string Code = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->Code = $var;

        return $this;
    }

    /**
     * json
     *
     * Generated from protobuf field <code>string Data = 5;</code>
     * @return string
     */
    public function getData()
    {
        return $this->Data;
    }

    /**
     * json
     *
     * Generated from protobuf field <code>string Data = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, True);
        $this->Data = $var;

        return $this;
    }

    /**
     * 给人看
     *
     * Generated from protobuf field <code>string Detail = 6;</code>
     * @return string
     */
    public function getDetail()
    {
        return $this->Detail;
    }

    /**
     * 给人看
     *
     * Generated from protobuf field <code>string Detail = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDetail($var)
    {
        GPBUtil::checkString($var, True);
        $this->Detail = $var;

        return $this;
    }

}

