<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: support.proto

namespace Shopex\Luban\Sdf;

/**
 * Protobuf enum <code>Luban\Gender</code>
 */
class Gender
{
    /**
     * Generated from protobuf enum <code>UNSET = 0;</code>
     */
    const PBUNSET = 0;
    /**
     * Generated from protobuf enum <code>MALE = 1;</code>
     */
    const MALE = 1;
    /**
     * Generated from protobuf enum <code>FEMALE = 2;</code>
     */
    const FEMALE = 2;
}

