<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shopex.proto

namespace Shopex\Luban\Sdf;

/**
 * Protobuf enum <code>Luban\Gender</code>
 */
class Gender
{
    /**
     * Generated from protobuf enum <code>MALE = 0;</code>
     */
    const MALE = 0;
    /**
     * Generated from protobuf enum <code>FEMALE = 1;</code>
     */
    const FEMALE = 1;
}

