<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade.proto

namespace Shopex\Luban\Sdf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *赠品券
 *
 * Generated from protobuf message <code>luban.Gift</code>
 */
class Gift extends \Google\Protobuf\Internal\Message
{
    /**
     *券 id
     *
     * Generated from protobuf field <code>int64 Id = 1;</code>
     */
    private $Id = 0;
    /**
     *券类型 id
     *
     * Generated from protobuf field <code>int64 CouponId = 2;</code>
     */
    private $CouponId = 0;
    /**
     *券名称
     *
     * Generated from protobuf field <code>string GiftName = 3;</code>
     */
    private $GiftName = '';
    /**
     *券图标
     *
     * Generated from protobuf field <code>string GiftLogo = 4;</code>
     */
    private $GiftLogo = '';
    /**
     *券代码
     *
     * Generated from protobuf field <code>string GiftToken = 5;</code>
     */
    private $GiftToken = '';
    /**
     *描述信息
     *
     * Generated from protobuf field <code>string GiftMemo = 6;</code>
     */
    private $GiftMemo = '';
    /**
     * Generated from protobuf field <code>repeated .luban.Meta Meta = 7;</code>
     */
    private $Meta;

    public function __construct() {
        \GPBMetadata\Trade::initOnce();
        parent::__construct();
    }

    /**
     *券 id
     *
     * Generated from protobuf field <code>int64 Id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->Id;
    }

    /**
     *券 id
     *
     * Generated from protobuf field <code>int64 Id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->Id = $var;

        return $this;
    }

    /**
     *券类型 id
     *
     * Generated from protobuf field <code>int64 CouponId = 2;</code>
     * @return int|string
     */
    public function getCouponId()
    {
        return $this->CouponId;
    }

    /**
     *券类型 id
     *
     * Generated from protobuf field <code>int64 CouponId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCouponId($var)
    {
        GPBUtil::checkInt64($var);
        $this->CouponId = $var;

        return $this;
    }

    /**
     *券名称
     *
     * Generated from protobuf field <code>string GiftName = 3;</code>
     * @return string
     */
    public function getGiftName()
    {
        return $this->GiftName;
    }

    /**
     *券名称
     *
     * Generated from protobuf field <code>string GiftName = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setGiftName($var)
    {
        GPBUtil::checkString($var, True);
        $this->GiftName = $var;

        return $this;
    }

    /**
     *券图标
     *
     * Generated from protobuf field <code>string GiftLogo = 4;</code>
     * @return string
     */
    public function getGiftLogo()
    {
        return $this->GiftLogo;
    }

    /**
     *券图标
     *
     * Generated from protobuf field <code>string GiftLogo = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setGiftLogo($var)
    {
        GPBUtil::checkString($var, True);
        $this->GiftLogo = $var;

        return $this;
    }

    /**
     *券代码
     *
     * Generated from protobuf field <code>string GiftToken = 5;</code>
     * @return string
     */
    public function getGiftToken()
    {
        return $this->GiftToken;
    }

    /**
     *券代码
     *
     * Generated from protobuf field <code>string GiftToken = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setGiftToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->GiftToken = $var;

        return $this;
    }

    /**
     *描述信息
     *
     * Generated from protobuf field <code>string GiftMemo = 6;</code>
     * @return string
     */
    public function getGiftMemo()
    {
        return $this->GiftMemo;
    }

    /**
     *描述信息
     *
     * Generated from protobuf field <code>string GiftMemo = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setGiftMemo($var)
    {
        GPBUtil::checkString($var, True);
        $this->GiftMemo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .luban.Meta Meta = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMeta()
    {
        return $this->Meta;
    }

    /**
     * Generated from protobuf field <code>repeated .luban.Meta Meta = 7;</code>
     * @param \Shopex\Luban\Sdf\Meta[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMeta($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Shopex\Luban\Sdf\Meta::class);
        $this->Meta = $arr;

        return $this;
    }

}

