<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shopex.proto

namespace Shopex\Luban\Sdf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>luban.Invoice</code>
 */
class Invoice extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.luban.Invoice.EnumMode Mode = 1;</code>
     */
    private $Mode = 0;
    /**
     * Generated from protobuf field <code>.luban.Invoice.EnumType Type = 2;</code>
     */
    private $Type = 0;
    /**
     *发票抬头
     *
     * Generated from protobuf field <code>string content = 4;</code>
     */
    private $content = '';
    /**
     *公司名称
     *
     * Generated from protobuf field <code>string company_name = 5;</code>
     */
    private $company_name = '';
    /**
     *公司地址
     *
     * Generated from protobuf field <code>string company_address = 6;</code>
     */
    private $company_address = '';
    /**
     *纳税人识别号
     *
     * Generated from protobuf field <code>string registration_number = 7;</code>
     */
    private $registration_number = '';
    /**
     *开户银行
     *
     * Generated from protobuf field <code>string bankname = 8;</code>
     */
    private $bankname = '';
    /**
     *开户银行帐号
     *
     * Generated from protobuf field <code>string bankaccount = 9;</code>
     */
    private $bankaccount = '';
    /**
     *公司电话
     *
     * Generated from protobuf field <code>string company_phone = 10;</code>
     */
    private $company_phone = '';

    public function __construct() {
        \GPBMetadata\Shopex::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.luban.Invoice.EnumMode Mode = 1;</code>
     * @return int
     */
    public function getMode()
    {
        return $this->Mode;
    }

    /**
     * Generated from protobuf field <code>.luban.Invoice.EnumMode Mode = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMode($var)
    {
        GPBUtil::checkEnum($var, \Shopex\Luban\Sdf\Invoice_EnumMode::class);
        $this->Mode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.luban.Invoice.EnumType Type = 2;</code>
     * @return int
     */
    public function getType()
    {
        return $this->Type;
    }

    /**
     * Generated from protobuf field <code>.luban.Invoice.EnumType Type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Shopex\Luban\Sdf\Invoice_EnumType::class);
        $this->Type = $var;

        return $this;
    }

    /**
     *发票抬头
     *
     * Generated from protobuf field <code>string content = 4;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     *发票抬头
     *
     * Generated from protobuf field <code>string content = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->content = $var;

        return $this;
    }

    /**
     *公司名称
     *
     * Generated from protobuf field <code>string company_name = 5;</code>
     * @return string
     */
    public function getCompanyName()
    {
        return $this->company_name;
    }

    /**
     *公司名称
     *
     * Generated from protobuf field <code>string company_name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCompanyName($var)
    {
        GPBUtil::checkString($var, True);
        $this->company_name = $var;

        return $this;
    }

    /**
     *公司地址
     *
     * Generated from protobuf field <code>string company_address = 6;</code>
     * @return string
     */
    public function getCompanyAddress()
    {
        return $this->company_address;
    }

    /**
     *公司地址
     *
     * Generated from protobuf field <code>string company_address = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setCompanyAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->company_address = $var;

        return $this;
    }

    /**
     *纳税人识别号
     *
     * Generated from protobuf field <code>string registration_number = 7;</code>
     * @return string
     */
    public function getRegistrationNumber()
    {
        return $this->registration_number;
    }

    /**
     *纳税人识别号
     *
     * Generated from protobuf field <code>string registration_number = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setRegistrationNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->registration_number = $var;

        return $this;
    }

    /**
     *开户银行
     *
     * Generated from protobuf field <code>string bankname = 8;</code>
     * @return string
     */
    public function getBankname()
    {
        return $this->bankname;
    }

    /**
     *开户银行
     *
     * Generated from protobuf field <code>string bankname = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setBankname($var)
    {
        GPBUtil::checkString($var, True);
        $this->bankname = $var;

        return $this;
    }

    /**
     *开户银行帐号
     *
     * Generated from protobuf field <code>string bankaccount = 9;</code>
     * @return string
     */
    public function getBankaccount()
    {
        return $this->bankaccount;
    }

    /**
     *开户银行帐号
     *
     * Generated from protobuf field <code>string bankaccount = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setBankaccount($var)
    {
        GPBUtil::checkString($var, True);
        $this->bankaccount = $var;

        return $this;
    }

    /**
     *公司电话
     *
     * Generated from protobuf field <code>string company_phone = 10;</code>
     * @return string
     */
    public function getCompanyPhone()
    {
        return $this->company_phone;
    }

    /**
     *公司电话
     *
     * Generated from protobuf field <code>string company_phone = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setCompanyPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->company_phone = $var;

        return $this;
    }

}

