<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade.proto

namespace Shopex\Luban\Sdf;

/**
 * Protobuf enum <code>Luban\Invoice\EnumType</code>
 */
class Invoice_EnumType
{
    /**
     * Generated from protobuf enum <code>INDIVIDUAL = 0;</code>
     */
    const INDIVIDUAL = 0;
    /**
     * Generated from protobuf enum <code>COMPANY = 1;</code>
     */
    const COMPANY = 1;
}

