<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade.proto

namespace Shopex\Luban\Sdf;

/**
 * Protobuf enum <code>Luban\Invoice\EnumMode</code>
 */
class Invoice_EnumMode
{
    /**
     *普通发票
     *
     * Generated from protobuf enum <code>NORMAL = 0;</code>
     */
    const NORMAL = 0;
    /**
     *增值税发票
     *
     * Generated from protobuf enum <code>VAT = 1;</code>
     */
    const VAT = 1;
}

