<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade.proto

namespace Shopex\Luban\Sdf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>luban.Invoice</code>
 */
class Invoice extends \Google\Protobuf\Internal\Message
{
    /**
     *发票模式
     *
     * Generated from protobuf field <code>.luban.Invoice.EnumMode Mode = 1;</code>
     */
    private $Mode = 0;
    /**
     *发票类型   
     *
     * Generated from protobuf field <code>.luban.Invoice.EnumType Type = 2;</code>
     */
    private $Type = 0;
    /**
     *发票抬头
     *
     * Generated from protobuf field <code>string Content = 4;</code>
     */
    private $Content = '';
    /**
     *公司名称
     *
     * Generated from protobuf field <code>string CompanyName = 5;</code>
     */
    private $CompanyName = '';
    /**
     *公司地址
     *
     * Generated from protobuf field <code>string CompanyAddress = 6;</code>
     */
    private $CompanyAddress = '';
    /**
     *纳税人识别号
     *
     * Generated from protobuf field <code>string RegistrationNumber = 7;</code>
     */
    private $RegistrationNumber = '';
    /**
     *开户银行
     *
     * Generated from protobuf field <code>string Bankname = 8;</code>
     */
    private $Bankname = '';
    /**
     *开户银行帐号
     *
     * Generated from protobuf field <code>string Bankaccount = 9;</code>
     */
    private $Bankaccount = '';
    /**
     *公司电话
     *
     * Generated from protobuf field <code>string CompanyPhone = 10;</code>
     */
    private $CompanyPhone = '';

    public function __construct() {
        \GPBMetadata\Trade::initOnce();
        parent::__construct();
    }

    /**
     *发票模式
     *
     * Generated from protobuf field <code>.luban.Invoice.EnumMode Mode = 1;</code>
     * @return int
     */
    public function getMode()
    {
        return $this->Mode;
    }

    /**
     *发票模式
     *
     * Generated from protobuf field <code>.luban.Invoice.EnumMode Mode = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMode($var)
    {
        GPBUtil::checkEnum($var, \Shopex\Luban\Sdf\Invoice_EnumMode::class);
        $this->Mode = $var;

        return $this;
    }

    /**
     *发票类型   
     *
     * Generated from protobuf field <code>.luban.Invoice.EnumType Type = 2;</code>
     * @return int
     */
    public function getType()
    {
        return $this->Type;
    }

    /**
     *发票类型   
     *
     * Generated from protobuf field <code>.luban.Invoice.EnumType Type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Shopex\Luban\Sdf\Invoice_EnumType::class);
        $this->Type = $var;

        return $this;
    }

    /**
     *发票抬头
     *
     * Generated from protobuf field <code>string Content = 4;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->Content;
    }

    /**
     *发票抬头
     *
     * Generated from protobuf field <code>string Content = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->Content = $var;

        return $this;
    }

    /**
     *公司名称
     *
     * Generated from protobuf field <code>string CompanyName = 5;</code>
     * @return string
     */
    public function getCompanyName()
    {
        return $this->CompanyName;
    }

    /**
     *公司名称
     *
     * Generated from protobuf field <code>string CompanyName = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCompanyName($var)
    {
        GPBUtil::checkString($var, True);
        $this->CompanyName = $var;

        return $this;
    }

    /**
     *公司地址
     *
     * Generated from protobuf field <code>string CompanyAddress = 6;</code>
     * @return string
     */
    public function getCompanyAddress()
    {
        return $this->CompanyAddress;
    }

    /**
     *公司地址
     *
     * Generated from protobuf field <code>string CompanyAddress = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setCompanyAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->CompanyAddress = $var;

        return $this;
    }

    /**
     *纳税人识别号
     *
     * Generated from protobuf field <code>string RegistrationNumber = 7;</code>
     * @return string
     */
    public function getRegistrationNumber()
    {
        return $this->RegistrationNumber;
    }

    /**
     *纳税人识别号
     *
     * Generated from protobuf field <code>string RegistrationNumber = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setRegistrationNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->RegistrationNumber = $var;

        return $this;
    }

    /**
     *开户银行
     *
     * Generated from protobuf field <code>string Bankname = 8;</code>
     * @return string
     */
    public function getBankname()
    {
        return $this->Bankname;
    }

    /**
     *开户银行
     *
     * Generated from protobuf field <code>string Bankname = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setBankname($var)
    {
        GPBUtil::checkString($var, True);
        $this->Bankname = $var;

        return $this;
    }

    /**
     *开户银行帐号
     *
     * Generated from protobuf field <code>string Bankaccount = 9;</code>
     * @return string
     */
    public function getBankaccount()
    {
        return $this->Bankaccount;
    }

    /**
     *开户银行帐号
     *
     * Generated from protobuf field <code>string Bankaccount = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setBankaccount($var)
    {
        GPBUtil::checkString($var, True);
        $this->Bankaccount = $var;

        return $this;
    }

    /**
     *公司电话
     *
     * Generated from protobuf field <code>string CompanyPhone = 10;</code>
     * @return string
     */
    public function getCompanyPhone()
    {
        return $this->CompanyPhone;
    }

    /**
     *公司电话
     *
     * Generated from protobuf field <code>string CompanyPhone = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setCompanyPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->CompanyPhone = $var;

        return $this;
    }

}

