<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: support.proto

namespace Shopex\Luban\Sdf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>luban.Location</code>
 */
class Location extends \Google\Protobuf\Internal\Message
{
    /**
     *省份
     *
     * Generated from protobuf field <code>string Province = 1;</code>
     */
    private $Province = '';
    /**
     *市
     *
     * Generated from protobuf field <code>string City = 2;</code>
     */
    private $City = '';
    /**
     *区
     *
     * Generated from protobuf field <code>string District = 3;</code>
     */
    private $District = '';
    /**
     *街道
     *
     * Generated from protobuf field <code>string SubDistrict = 4;</code>
     */
    private $SubDistrict = '';
    /**
     * Generated from protobuf field <code>string Zip = 5;</code>
     */
    private $Zip = '';

    public function __construct() {
        \GPBMetadata\Support::initOnce();
        parent::__construct();
    }

    /**
     *省份
     *
     * Generated from protobuf field <code>string Province = 1;</code>
     * @return string
     */
    public function getProvince()
    {
        return $this->Province;
    }

    /**
     *省份
     *
     * Generated from protobuf field <code>string Province = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setProvince($var)
    {
        GPBUtil::checkString($var, True);
        $this->Province = $var;

        return $this;
    }

    /**
     *市
     *
     * Generated from protobuf field <code>string City = 2;</code>
     * @return string
     */
    public function getCity()
    {
        return $this->City;
    }

    /**
     *市
     *
     * Generated from protobuf field <code>string City = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->City = $var;

        return $this;
    }

    /**
     *区
     *
     * Generated from protobuf field <code>string District = 3;</code>
     * @return string
     */
    public function getDistrict()
    {
        return $this->District;
    }

    /**
     *区
     *
     * Generated from protobuf field <code>string District = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDistrict($var)
    {
        GPBUtil::checkString($var, True);
        $this->District = $var;

        return $this;
    }

    /**
     *街道
     *
     * Generated from protobuf field <code>string SubDistrict = 4;</code>
     * @return string
     */
    public function getSubDistrict()
    {
        return $this->SubDistrict;
    }

    /**
     *街道
     *
     * Generated from protobuf field <code>string SubDistrict = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSubDistrict($var)
    {
        GPBUtil::checkString($var, True);
        $this->SubDistrict = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Zip = 5;</code>
     * @return string
     */
    public function getZip()
    {
        return $this->Zip;
    }

    /**
     * Generated from protobuf field <code>string Zip = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setZip($var)
    {
        GPBUtil::checkString($var, True);
        $this->Zip = $var;

        return $this;
    }

}

