<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: support.proto

namespace Shopex\Luban\Sdf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>luban.Meta</code>
 */
class Meta extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Code = 1;</code>
     */
    private $Code = '';
    /**
     * Generated from protobuf field <code>string Value = 3;</code>
     */
    private $Value = '';

    public function __construct() {
        \GPBMetadata\Support::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string Code = 1;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->Code;
    }

    /**
     * Generated from protobuf field <code>string Code = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->Code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Value = 3;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->Value;
    }

    /**
     * Generated from protobuf field <code>string Value = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->Value = $var;

        return $this;
    }

}

