<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade.proto

namespace Shopex\Luban\Sdf;

/**
 * Protobuf enum <code>Luban\OrderType</code>
 */
class OrderType
{
    /**
     * Generated from protobuf enum <code>PHYSICAL = 0;</code>
     */
    const PHYSICAL = 0;
    /**
     * Generated from protobuf enum <code>DIGTAL = 1;</code>
     */
    const DIGTAL = 1;
}

