<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade.proto

namespace Shopex\Luban\Sdf;

/**
 * Protobuf enum <code>Luban\OrderType</code>
 */
class OrderType
{
    /**
     * 商品
     *
     * Generated from protobuf enum <code>GOODS = 0;</code>
     */
    const GOODS = 0;
    /**
     * 赠品
     *
     * Generated from protobuf enum <code>GIFT = 1;</code>
     */
    const GIFT = 1;
}

