<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shopex.proto

namespace Shopex\Luban\Sdf;

/**
 * Protobuf enum <code>Luban\PaymentStatus</code>
 */
class PaymentStatus
{
    /**
     * 等待买家付款
     *
     * Generated from protobuf enum <code>WAIT_BUYER_PAY = 0;</code>
     */
    const WAIT_BUYER_PAY = 0;
    /**
     * 买家已付款
     *
     * Generated from protobuf enum <code>BUYER_FULL_PAYED = 1;</code>
     */
    const BUYER_FULL_PAYED = 1;
    /**
     * 买家已部分付款
     *
     * Generated from protobuf enum <code>BUYER_PART_PAYED = 2;</code>
     */
    const BUYER_PART_PAYED = 2;
    /**
     * 付款信息确认中
     *
     * Generated from protobuf enum <code>TRADE_PAY_PENDING = 3;</code>
     */
    const TRADE_PAY_PENDING = 3;
}

