<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment.proto

namespace Shopex\Luban\Sdf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>luban.Payment</code>
 */
class Payment extends \Google\Protobuf\Internal\Message
{
    /**
     * 付款单号
     *
     * Generated from protobuf field <code>string PaymentId = 1;</code>
     */
    private $PaymentId = '';
    /**
     * 订单号
     *
     * Generated from protobuf field <code>string Tid = 2;</code>
     */
    private $Tid = '';
    /**
     * 支付金额
     *
     * Generated from protobuf field <code>double Amount = 3;</code>
     */
    private $Amount = 0.0;
    /**
     * 货币类型
     *
     * Generated from protobuf field <code>string Currency = 4;</code>
     */
    private $Currency = '';
    /**
     * 货币金额
     *
     * Generated from protobuf field <code>double CurrencyAmount = 5;</code>
     */
    private $CurrencyAmount = 0.0;
    /**
     * alipay-h5  alipay-app 具体支付方法
     *
     * Generated from protobuf field <code>string Method = 6;</code>
     */
    private $Method = '';
    /**
     * 支付渠道
     *
     * Generated from protobuf field <code>string Channel = 7;</code>
     */
    private $Channel = '';
    /**
     * Generated from protobuf field <code>.luban.PaymentType Type = 8;</code>
     */
    private $Type = 0;
    /**
     * Generated from protobuf field <code>.luban.PaymentStatus Status = 9;</code>
     */
    private $Status = 0;
    /**
     * Generated from protobuf field <code>string ErrMessage = 11;</code>
     */
    private $ErrMessage = '';
    /**
     *支付流水号
     *
     * Generated from protobuf field <code>string TransId = 12;</code>
     */
    private $TransId = '';
    /**
     *创建时间, status=ready
     *
     * Generated from protobuf field <code>int64 CreateTime = 13;</code>
     */
    private $CreateTime = 0;
    /**
     *付款超时时间
     *
     * Generated from protobuf field <code>int64 ExpireTime = 14;</code>
     */
    private $ExpireTime = 0;
    /**
     *支付时间, status=SUCC
     *
     * Generated from protobuf field <code>int64 PayTime = 15;</code>
     */
    private $PayTime = 0;
    /**
     *交易完成时间, status=CANCEL/ERROR/SUCC
     *
     * Generated from protobuf field <code>int64 EndTime = 16;</code>
     */
    private $EndTime = 0;
    /**
     * Generated from protobuf field <code>repeated .luban.Meta Meta = 20;</code>
     */
    private $Meta;

    public function __construct() {
        \GPBMetadata\Payment::initOnce();
        parent::__construct();
    }

    /**
     * 付款单号
     *
     * Generated from protobuf field <code>string PaymentId = 1;</code>
     * @return string
     */
    public function getPaymentId()
    {
        return $this->PaymentId;
    }

    /**
     * 付款单号
     *
     * Generated from protobuf field <code>string PaymentId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPaymentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->PaymentId = $var;

        return $this;
    }

    /**
     * 订单号
     *
     * Generated from protobuf field <code>string Tid = 2;</code>
     * @return string
     */
    public function getTid()
    {
        return $this->Tid;
    }

    /**
     * 订单号
     *
     * Generated from protobuf field <code>string Tid = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTid($var)
    {
        GPBUtil::checkString($var, True);
        $this->Tid = $var;

        return $this;
    }

    /**
     * 支付金额
     *
     * Generated from protobuf field <code>double Amount = 3;</code>
     * @return float
     */
    public function getAmount()
    {
        return $this->Amount;
    }

    /**
     * 支付金额
     *
     * Generated from protobuf field <code>double Amount = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkDouble($var);
        $this->Amount = $var;

        return $this;
    }

    /**
     * 货币类型
     *
     * Generated from protobuf field <code>string Currency = 4;</code>
     * @return string
     */
    public function getCurrency()
    {
        return $this->Currency;
    }

    /**
     * 货币类型
     *
     * Generated from protobuf field <code>string Currency = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrency($var)
    {
        GPBUtil::checkString($var, True);
        $this->Currency = $var;

        return $this;
    }

    /**
     * 货币金额
     *
     * Generated from protobuf field <code>double CurrencyAmount = 5;</code>
     * @return float
     */
    public function getCurrencyAmount()
    {
        return $this->CurrencyAmount;
    }

    /**
     * 货币金额
     *
     * Generated from protobuf field <code>double CurrencyAmount = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setCurrencyAmount($var)
    {
        GPBUtil::checkDouble($var);
        $this->CurrencyAmount = $var;

        return $this;
    }

    /**
     * alipay-h5  alipay-app 具体支付方法
     *
     * Generated from protobuf field <code>string Method = 6;</code>
     * @return string
     */
    public function getMethod()
    {
        return $this->Method;
    }

    /**
     * alipay-h5  alipay-app 具体支付方法
     *
     * Generated from protobuf field <code>string Method = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setMethod($var)
    {
        GPBUtil::checkString($var, True);
        $this->Method = $var;

        return $this;
    }

    /**
     * 支付渠道
     *
     * Generated from protobuf field <code>string Channel = 7;</code>
     * @return string
     */
    public function getChannel()
    {
        return $this->Channel;
    }

    /**
     * 支付渠道
     *
     * Generated from protobuf field <code>string Channel = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setChannel($var)
    {
        GPBUtil::checkString($var, True);
        $this->Channel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.luban.PaymentType Type = 8;</code>
     * @return int
     */
    public function getType()
    {
        return $this->Type;
    }

    /**
     * Generated from protobuf field <code>.luban.PaymentType Type = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Shopex\Luban\Sdf\PaymentType::class);
        $this->Type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.luban.PaymentStatus Status = 9;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->Status;
    }

    /**
     * Generated from protobuf field <code>.luban.PaymentStatus Status = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Shopex\Luban\Sdf\PaymentStatus::class);
        $this->Status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ErrMessage = 11;</code>
     * @return string
     */
    public function getErrMessage()
    {
        return $this->ErrMessage;
    }

    /**
     * Generated from protobuf field <code>string ErrMessage = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setErrMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->ErrMessage = $var;

        return $this;
    }

    /**
     *支付流水号
     *
     * Generated from protobuf field <code>string TransId = 12;</code>
     * @return string
     */
    public function getTransId()
    {
        return $this->TransId;
    }

    /**
     *支付流水号
     *
     * Generated from protobuf field <code>string TransId = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setTransId($var)
    {
        GPBUtil::checkString($var, True);
        $this->TransId = $var;

        return $this;
    }

    /**
     *创建时间, status=ready
     *
     * Generated from protobuf field <code>int64 CreateTime = 13;</code>
     * @return int|string
     */
    public function getCreateTime()
    {
        return $this->CreateTime;
    }

    /**
     *创建时间, status=ready
     *
     * Generated from protobuf field <code>int64 CreateTime = 13;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreateTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->CreateTime = $var;

        return $this;
    }

    /**
     *付款超时时间
     *
     * Generated from protobuf field <code>int64 ExpireTime = 14;</code>
     * @return int|string
     */
    public function getExpireTime()
    {
        return $this->ExpireTime;
    }

    /**
     *付款超时时间
     *
     * Generated from protobuf field <code>int64 ExpireTime = 14;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpireTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->ExpireTime = $var;

        return $this;
    }

    /**
     *支付时间, status=SUCC
     *
     * Generated from protobuf field <code>int64 PayTime = 15;</code>
     * @return int|string
     */
    public function getPayTime()
    {
        return $this->PayTime;
    }

    /**
     *支付时间, status=SUCC
     *
     * Generated from protobuf field <code>int64 PayTime = 15;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPayTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->PayTime = $var;

        return $this;
    }

    /**
     *交易完成时间, status=CANCEL/ERROR/SUCC
     *
     * Generated from protobuf field <code>int64 EndTime = 16;</code>
     * @return int|string
     */
    public function getEndTime()
    {
        return $this->EndTime;
    }

    /**
     *交易完成时间, status=CANCEL/ERROR/SUCC
     *
     * Generated from protobuf field <code>int64 EndTime = 16;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEndTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->EndTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .luban.Meta Meta = 20;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMeta()
    {
        return $this->Meta;
    }

    /**
     * Generated from protobuf field <code>repeated .luban.Meta Meta = 20;</code>
     * @param \Shopex\Luban\Sdf\Meta[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMeta($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Shopex\Luban\Sdf\Meta::class);
        $this->Meta = $arr;

        return $this;
    }

}

