<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment.proto

namespace Shopex\Luban\Sdf;

/**
 * Protobuf enum <code>Luban\PaymentType</code>
 */
class PaymentType
{
    /**
     * Generated from protobuf enum <code>ONLINE = 0;</code>
     */
    const ONLINE = 0;
    /**
     * Generated from protobuf enum <code>OFFLINE = 1;</code>
     */
    const OFFLINE = 1;
    /**
     * Generated from protobuf enum <code>DEPOSIT = 2;</code>
     */
    const DEPOSIT = 2;
}

