<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment.proto

namespace Shopex\Luban\Sdf;

/**
 * Protobuf enum <code>Luban\PaymentStatus</code>
 */
class PaymentStatus
{
    /**
     *未支付
     *
     * Generated from protobuf enum <code>READY = 0;</code>
     */
    const READY = 0;
    /**
     *支付成功
     *
     * Generated from protobuf enum <code>SUCC = 1;</code>
     */
    const SUCC = 1;
    /**
     *支付错误
     *
     * Generated from protobuf enum <code>ERROR = 2;</code>
     */
    const ERROR = 2;
    /**
     *用户取消支付
     *
     * Generated from protobuf enum <code>CANCEL = 3;</code>
     */
    const CANCEL = 3;
}

