<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: support.proto

namespace Shopex\Luban\Sdf;

/**
 * Protobuf enum <code>Luban\SearchFilter\Op</code>
 */
class SearchFilter_Op
{
    /**
     * than 大于 >
     *
     * Generated from protobuf enum <code>THAN = 0;</code>
     */
    const THAN = 0;
    /**
     * lthan 小与 <
     *
     * Generated from protobuf enum <code>LTHAN = 1;</code>
     */
    const LTHAN = 1;
    /**
     * nequal  ==
     *
     * Generated from protobuf enum <code>NEQUAL = 2;</code>
     */
    const NEQUAL = 2;
    /**
     * tequal ==
     *
     * Generated from protobuf enum <code>TEQUAL = 3;</code>
     */
    const TEQUAL = 3;
    /**
     * noequal !=
     *
     * Generated from protobuf enum <code>NOEQUAL = 4;</code>
     */
    const NOEQUAL = 4;
    /**
     * sthan <=
     *
     * Generated from protobuf enum <code>STHAN = 5;</code>
     */
    const STHAN = 5;
    /**
     * bthan >=
     *
     * Generated from protobuf enum <code>BTHAN = 6;</code>
     */
    const BTHAN = 6;
    /**
     * has LIKE %has%
     *
     * Generated from protobuf enum <code>HAS = 7;</code>
     */
    const HAS = 7;
    /**
     * head LIKE has%
     *
     * Generated from protobuf enum <code>HEAD = 8;</code>
     */
    const HEAD = 8;
    /**
     * foot LIKE %has
     *
     * Generated from protobuf enum <code>FOOT = 9;</code>
     */
    const FOOT = 9;
    /**
     * nohas NOT LIKE
     *
     * Generated from protobuf enum <code>NOHAS = 12;</code>
     */
    const NOHAS = 12;
    /**
     * between
     *
     * Generated from protobuf enum <code>BETWEEN = 13;</code>
     */
    const BETWEEN = 13;
    /**
     * in IN
     *
     * Generated from protobuf enum <code>IN = 14;</code>
     */
    const IN = 14;
    /**
     *not in  NOT IN
     *
     * Generated from protobuf enum <code>NOTIN = 15;</code>
     */
    const NOTIN = 15;
    /**
     * is null
     *
     * Generated from protobuf enum <code>ISNULL = 16;</code>
     */
    const ISNULL = 16;
    /**
     *is not null
     *
     * Generated from protobuf enum <code>ISNOTNULL = 17;</code>
     */
    const ISNOTNULL = 17;
}

