<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shopex.proto

namespace Shopex\Luban\Sdf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>luban.SearchRequest</code>
 */
class SearchRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Columns = 1;</code>
     */
    private $Columns = '';
    /**
     * Generated from protobuf field <code>repeated .luban.SearchFilter Filter = 2;</code>
     */
    private $Filter;
    /**
     * Generated from protobuf field <code>int64 Offset = 3;</code>
     */
    private $Offset = 0;
    /**
     * Generated from protobuf field <code>int64 Limit = 4;</code>
     */
    private $Limit = 0;
    /**
     * Generated from protobuf field <code>string OrderBy = 5;</code>
     */
    private $OrderBy = '';

    public function __construct() {
        \GPBMetadata\Shopex::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string Columns = 1;</code>
     * @return string
     */
    public function getColumns()
    {
        return $this->Columns;
    }

    /**
     * Generated from protobuf field <code>string Columns = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setColumns($var)
    {
        GPBUtil::checkString($var, True);
        $this->Columns = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .luban.SearchFilter Filter = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFilter()
    {
        return $this->Filter;
    }

    /**
     * Generated from protobuf field <code>repeated .luban.SearchFilter Filter = 2;</code>
     * @param \Shopex\Luban\Sdf\SearchFilter[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFilter($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Shopex\Luban\Sdf\SearchFilter::class);
        $this->Filter = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 Offset = 3;</code>
     * @return int|string
     */
    public function getOffset()
    {
        return $this->Offset;
    }

    /**
     * Generated from protobuf field <code>int64 Offset = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOffset($var)
    {
        GPBUtil::checkInt64($var);
        $this->Offset = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 Limit = 4;</code>
     * @return int|string
     */
    public function getLimit()
    {
        return $this->Limit;
    }

    /**
     * Generated from protobuf field <code>int64 Limit = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkInt64($var);
        $this->Limit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string OrderBy = 5;</code>
     * @return string
     */
    public function getOrderBy()
    {
        return $this->OrderBy;
    }

    /**
     * Generated from protobuf field <code>string OrderBy = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderBy($var)
    {
        GPBUtil::checkString($var, True);
        $this->OrderBy = $var;

        return $this;
    }

}

