<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shipment.proto

namespace Shopex\Luban\Sdf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>luban.ShipItem</code>
 */
class ShipItem extends \Google\Protobuf\Internal\Message
{
    /**
     *商品id
     *
     * Generated from protobuf field <code>string SkuId = 1;</code>
     */
    private $SkuId = '';
    /**
     *数量
     *
     * Generated from protobuf field <code>int64 Quantity = 2;</code>
     */
    private $Quantity = 0;
    /**
     * Generated from protobuf field <code>string OrderId = 3;</code>
     */
    private $OrderId = '';

    public function __construct() {
        \GPBMetadata\Shipment::initOnce();
        parent::__construct();
    }

    /**
     *商品id
     *
     * Generated from protobuf field <code>string SkuId = 1;</code>
     * @return string
     */
    public function getSkuId()
    {
        return $this->SkuId;
    }

    /**
     *商品id
     *
     * Generated from protobuf field <code>string SkuId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSkuId($var)
    {
        GPBUtil::checkString($var, True);
        $this->SkuId = $var;

        return $this;
    }

    /**
     *数量
     *
     * Generated from protobuf field <code>int64 Quantity = 2;</code>
     * @return int|string
     */
    public function getQuantity()
    {
        return $this->Quantity;
    }

    /**
     *数量
     *
     * Generated from protobuf field <code>int64 Quantity = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setQuantity($var)
    {
        GPBUtil::checkInt64($var);
        $this->Quantity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string OrderId = 3;</code>
     * @return string
     */
    public function getOrderId()
    {
        return $this->OrderId;
    }

    /**
     * Generated from protobuf field <code>string OrderId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderId($var)
    {
        GPBUtil::checkString($var, True);
        $this->OrderId = $var;

        return $this;
    }

}

