<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade.proto

namespace Shopex\Luban\Sdf;

/**
 * Protobuf enum <code>Luban\ShippingStatus</code>
 */
class ShippingStatus
{
    /**
     *未开始处理
     *
     * Generated from protobuf enum <code>NEW = 0;</code>
     */
    const PBNEW = 0;
    /**
     *仓库接单 
     *
     * Generated from protobuf enum <code>ACCEPT = 1;</code>
     */
    const ACCEPT = 1;
    /**
     *部分发货完成
     *
     * Generated from protobuf enum <code>PARTDELIVERED = 2;</code>
     */
    const PARTDELIVERED = 2;
    /**
     *发货完成
     *
     * Generated from protobuf enum <code>DELIVERED = 3;</code>
     */
    const DELIVERED = 3;
    /**
     *异常
     *
     * Generated from protobuf enum <code>EXCEPTION = 4;</code>
     */
    const EXCEPTION = 4;
    /**
     *取消
     *
     * Generated from protobuf enum <code>CANCELED = 5;</code>
     */
    const CANCELED = 5;
    /**
     *关闭
     *
     * Generated from protobuf enum <code>CLOSED = 6;</code>
     */
    const CLOSED = 6;
    /**
     *拒单
     *
     * Generated from protobuf enum <code>REJECT = 7;</code>
     */
    const REJECT = 7;
    /**
     *取消失败
     *
     * Generated from protobuf enum <code>CANCELEDFAIL = 8;</code>
     */
    const CANCELEDFAIL = 8;
}

