<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shipment.proto

namespace Shopex\Luban\Sdf;

/**
 * Protobuf enum <code>Luban\Shipment\EnumStatus</code>
 */
class Shipment_EnumStatus
{
    /**
     * Generated from protobuf enum <code>WAIT_BUYER_PAY = 0;</code>
     */
    const WAIT_BUYER_PAY = 0;
    /**
     * Generated from protobuf enum <code>PAY_SUCCESS = 1;</code>
     */
    const PAY_SUCCESS = 1;
}

