<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shipment.proto

namespace Shopex\Luban\Sdf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>luban.Shipment</code>
 */
class Shipment extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Tid = 1;</code>
     */
    private $Tid = '';
    /**
     * Generated from protobuf field <code>string Carrier = 2;</code>
     */
    private $Carrier = '';
    /**
     * Generated from protobuf field <code>string TrackNumber = 3;</code>
     */
    private $TrackNumber = '';
    /**
     * Generated from protobuf field <code>.luban.Shipment.EnumStatus Status = 4;</code>
     */
    private $Status = 0;
    /**
     * Generated from protobuf field <code>repeated .luban.Meta Meta = 5;</code>
     */
    private $Meta;

    public function __construct() {
        \GPBMetadata\Shipment::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string Tid = 1;</code>
     * @return string
     */
    public function getTid()
    {
        return $this->Tid;
    }

    /**
     * Generated from protobuf field <code>string Tid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTid($var)
    {
        GPBUtil::checkString($var, True);
        $this->Tid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Carrier = 2;</code>
     * @return string
     */
    public function getCarrier()
    {
        return $this->Carrier;
    }

    /**
     * Generated from protobuf field <code>string Carrier = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCarrier($var)
    {
        GPBUtil::checkString($var, True);
        $this->Carrier = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string TrackNumber = 3;</code>
     * @return string
     */
    public function getTrackNumber()
    {
        return $this->TrackNumber;
    }

    /**
     * Generated from protobuf field <code>string TrackNumber = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTrackNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->TrackNumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.luban.Shipment.EnumStatus Status = 4;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->Status;
    }

    /**
     * Generated from protobuf field <code>.luban.Shipment.EnumStatus Status = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Shopex\Luban\Sdf\Shipment_EnumStatus::class);
        $this->Status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .luban.Meta Meta = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMeta()
    {
        return $this->Meta;
    }

    /**
     * Generated from protobuf field <code>repeated .luban.Meta Meta = 5;</code>
     * @param \Shopex\Luban\Sdf\Meta[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMeta($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Shopex\Luban\Sdf\Meta::class);
        $this->Meta = $arr;

        return $this;
    }

}

