<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shopex.proto

namespace Shopex\Luban\Sdf;

/**
 * Protobuf enum <code>Luban\ShipmentStatus</code>
 */
class ShipmentStatus
{
    /**
     * 等待卖家发货
     *
     * Generated from protobuf enum <code>WAIT_SELLER_SEND_GOODS = 0;</code>
     */
    const WAIT_SELLER_SEND_GOODS = 0;
    /**
     * 等待买家确认收货,即:卖家已发货
     *
     * Generated from protobuf enum <code>WAIT_BUYER_CONFIRM_GOODS = 1;</code>
     */
    const WAIT_BUYER_CONFIRM_GOODS = 1;
    /**
     * 买家已签收,货到付款专用
     *
     * Generated from protobuf enum <code>TRADE_BUYER_SIGNED = 2;</code>
     */
    const TRADE_BUYER_SIGNED = 2;
}

