<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shipment.proto

namespace Shopex\Luban\Sdf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>luban.Shipment</code>
 */
class Shipment extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Tid = 1;</code>
     */
    private $Tid = '';
    /**
     * Generated from protobuf field <code>string Carrier = 2;</code>
     */
    private $Carrier = '';
    /**
     * Generated from protobuf field <code>string TrackNumber = 3;</code>
     */
    private $TrackNumber = '';
    /**
     *创建时间	
     *
     * Generated from protobuf field <code>int64 CreateTime = 7;</code>
     */
    private $CreateTime = 0;
    /**
     * Generated from protobuf field <code>repeated .luban.ShipItem Items = 8;</code>
     */
    private $Items;
    /**
     * Generated from protobuf field <code>repeated .luban.Meta Meta = 10;</code>
     */
    private $Meta;

    public function __construct() {
        \GPBMetadata\Shipment::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string Tid = 1;</code>
     * @return string
     */
    public function getTid()
    {
        return $this->Tid;
    }

    /**
     * Generated from protobuf field <code>string Tid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTid($var)
    {
        GPBUtil::checkString($var, True);
        $this->Tid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Carrier = 2;</code>
     * @return string
     */
    public function getCarrier()
    {
        return $this->Carrier;
    }

    /**
     * Generated from protobuf field <code>string Carrier = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCarrier($var)
    {
        GPBUtil::checkString($var, True);
        $this->Carrier = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string TrackNumber = 3;</code>
     * @return string
     */
    public function getTrackNumber()
    {
        return $this->TrackNumber;
    }

    /**
     * Generated from protobuf field <code>string TrackNumber = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTrackNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->TrackNumber = $var;

        return $this;
    }

    /**
     *创建时间	
     *
     * Generated from protobuf field <code>int64 CreateTime = 7;</code>
     * @return int|string
     */
    public function getCreateTime()
    {
        return $this->CreateTime;
    }

    /**
     *创建时间	
     *
     * Generated from protobuf field <code>int64 CreateTime = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreateTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->CreateTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .luban.ShipItem Items = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->Items;
    }

    /**
     * Generated from protobuf field <code>repeated .luban.ShipItem Items = 8;</code>
     * @param \Shopex\Luban\Sdf\ShipItem[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Shopex\Luban\Sdf\ShipItem::class);
        $this->Items = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .luban.Meta Meta = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMeta()
    {
        return $this->Meta;
    }

    /**
     * Generated from protobuf field <code>repeated .luban.Meta Meta = 10;</code>
     * @param \Shopex\Luban\Sdf\Meta[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMeta($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Shopex\Luban\Sdf\Meta::class);
        $this->Meta = $arr;

        return $this;
    }

}

