<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade.proto

namespace Shopex\Luban\Sdf;

/**
 * Protobuf enum <code>Luban\ShippingStatus</code>
 */
class ShippingStatus
{
    /**
     * 未处理
     *
     * Generated from protobuf enum <code>SHIP_UNPROCESS = 0;</code>
     */
    const SHIP_UNPROCESS = 0;
    /**
     * 配货中
     *
     * Generated from protobuf enum <code>SHIP_ALLOCATION = 1;</code>
     */
    const SHIP_ALLOCATION = 1;
    /**
     * 已发货
     *
     * Generated from protobuf enum <code>SHIP_ALL_SHIPPED = 2;</code>
     */
    const SHIP_ALL_SHIPPED = 2;
    /**
     * 部分发货
     *
     * Generated from protobuf enum <code>SHIP_PART_SHIPPED = 3;</code>
     */
    const SHIP_PART_SHIPPED = 3;
}

