<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: svc_stocker.proto

namespace Shopex\Luban\Sdf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>luban.StockSetResponse</code>
 */
class StockSetResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string ItemKey = 1;</code>
     */
    private $ItemKey = '';
    /**
     * Generated from protobuf field <code>int64 Changed = 2;</code>
     */
    private $Changed = 0;

    public function __construct() {
        \GPBMetadata\SvcStocker::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string ItemKey = 1;</code>
     * @return string
     */
    public function getItemKey()
    {
        return $this->ItemKey;
    }

    /**
     * Generated from protobuf field <code>string ItemKey = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setItemKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->ItemKey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 Changed = 2;</code>
     * @return int|string
     */
    public function getChanged()
    {
        return $this->Changed;
    }

    /**
     * Generated from protobuf field <code>int64 Changed = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setChanged($var)
    {
        GPBUtil::checkInt64($var);
        $this->Changed = $var;

        return $this;
    }

}

