<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stocker.proto

namespace Shopex\Luban\Sdf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>luban.StockGetRequest</code>
 */
class StockGetRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string ItemKey = 1;</code>
     */
    private $ItemKey = '';

    public function __construct() {
        \GPBMetadata\Stocker::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string ItemKey = 1;</code>
     * @return string
     */
    public function getItemKey()
    {
        return $this->ItemKey;
    }

    /**
     * Generated from protobuf field <code>string ItemKey = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setItemKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->ItemKey = $var;

        return $this;
    }

}

