<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: svc_stocker.proto

namespace Shopex\Luban\Sdf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>luban.StockBatchGetRequest</code>
 */
class StockBatchGetRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string ItemKey = 1;</code>
     */
    private $ItemKey;

    public function __construct() {
        \GPBMetadata\SvcStocker::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated string ItemKey = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItemKey()
    {
        return $this->ItemKey;
    }

    /**
     * Generated from protobuf field <code>repeated string ItemKey = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItemKey($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->ItemKey = $arr;

        return $this;
    }

}

