<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: svc_stocker.proto

namespace Shopex\Luban\Sdf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>luban.StockGetResponse</code>
 */
class StockGetResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 Number = 1;</code>
     */
    private $Number = 0;

    public function __construct() {
        \GPBMetadata\SvcStocker::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int64 Number = 1;</code>
     * @return int|string
     */
    public function getNumber()
    {
        return $this->Number;
    }

    /**
     * Generated from protobuf field <code>int64 Number = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNumber($var)
    {
        GPBUtil::checkInt64($var);
        $this->Number = $var;

        return $this;
    }

}

