<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shopex.proto

namespace Shopex\Luban\Sdf;

/**
 * Protobuf enum <code>Luban\TradeStatus</code>
 */
class TradeStatus
{
    /**
     * 进行中
     *
     * Generated from protobuf enum <code>TRADE_OPEN = 0;</code>
     */
    const TRADE_OPEN = 0;
    /**
     * 已完成
     *
     * Generated from protobuf enum <code>TRADE_FINISHED = 1;</code>
     */
    const TRADE_FINISHED = 1;
    /**
     * 已作废
     *
     * Generated from protobuf enum <code>TRADE_CLOSED = 2;</code>
     */
    const TRADE_CLOSED = 2;
}

