<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dealer.proto

namespace Shopex\Luban\Sdf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>luban.TradeListResponse</code>
 */
class TradeListResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.luban.Trade Trade = 1;</code>
     */
    private $Trade = null;

    public function __construct() {
        \GPBMetadata\Dealer::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.luban.Trade Trade = 1;</code>
     * @return \Shopex\Luban\Sdf\Trade
     */
    public function getTrade()
    {
        return $this->Trade;
    }

    /**
     * Generated from protobuf field <code>.luban.Trade Trade = 1;</code>
     * @param \Shopex\Luban\Sdf\Trade $var
     * @return $this
     */
    public function setTrade($var)
    {
        GPBUtil::checkMessage($var, \Shopex\Luban\Sdf\Trade::class);
        $this->Trade = $var;

        return $this;
    }

}

