<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dealer.proto

namespace Shopex\Luban\Sdf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>luban.TradeInfoRequest</code>
 */
class TradeInfoRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string TradeId = 1;</code>
     */
    private $TradeId = '';

    public function __construct() {
        \GPBMetadata\Dealer::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string TradeId = 1;</code>
     * @return string
     */
    public function getTradeId()
    {
        return $this->TradeId;
    }

    /**
     * Generated from protobuf field <code>string TradeId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTradeId($var)
    {
        GPBUtil::checkString($var, True);
        $this->TradeId = $var;

        return $this;
    }

}

