<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dealer.proto

namespace Shopex\Luban\Sdf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>luban.TradeListResponse</code>
 */
class TradeListResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .luban.Trade Trade = 1;</code>
     */
    private $Trade;
    /**
     * Generated from protobuf field <code>int64 Count = 2;</code>
     */
    private $Count = 0;

    public function __construct() {
        \GPBMetadata\Dealer::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .luban.Trade Trade = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTrade()
    {
        return $this->Trade;
    }

    /**
     * Generated from protobuf field <code>repeated .luban.Trade Trade = 1;</code>
     * @param \Shopex\Luban\Sdf\Trade[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTrade($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Shopex\Luban\Sdf\Trade::class);
        $this->Trade = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 Count = 2;</code>
     * @return int|string
     */
    public function getCount()
    {
        return $this->Count;
    }

    /**
     * Generated from protobuf field <code>int64 Count = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->Count = $var;

        return $this;
    }

}

