<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dealer.proto

namespace Shopex\Luban\Sdf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>luban.TradePayResponse</code>
 */
class TradePayResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string TradeBn = 1;</code>
     */
    private $TradeBn = '';

    public function __construct() {
        \GPBMetadata\Dealer::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string TradeBn = 1;</code>
     * @return string
     */
    public function getTradeBn()
    {
        return $this->TradeBn;
    }

    /**
     * Generated from protobuf field <code>string TradeBn = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTradeBn($var)
    {
        GPBUtil::checkString($var, True);
        $this->TradeBn = $var;

        return $this;
    }

}

