<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: svc_dealer.proto

namespace Shopex\Luban\Sdf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>luban.TradeShipRequest</code>
 */
class TradeShipRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Tid = 1;</code>
     */
    private $Tid = '';
    /**
     * Generated from protobuf field <code>string ShipStatus = 2;</code>
     */
    private $ShipStatus = '';
    /**
     * Generated from protobuf field <code>string Carrier = 3;</code>
     */
    private $Carrier = '';
    /**
     * Generated from protobuf field <code>string TrackNumber = 4;</code>
     */
    private $TrackNumber = '';

    public function __construct() {
        \GPBMetadata\SvcDealer::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string Tid = 1;</code>
     * @return string
     */
    public function getTid()
    {
        return $this->Tid;
    }

    /**
     * Generated from protobuf field <code>string Tid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTid($var)
    {
        GPBUtil::checkString($var, True);
        $this->Tid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ShipStatus = 2;</code>
     * @return string
     */
    public function getShipStatus()
    {
        return $this->ShipStatus;
    }

    /**
     * Generated from protobuf field <code>string ShipStatus = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setShipStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->ShipStatus = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Carrier = 3;</code>
     * @return string
     */
    public function getCarrier()
    {
        return $this->Carrier;
    }

    /**
     * Generated from protobuf field <code>string Carrier = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCarrier($var)
    {
        GPBUtil::checkString($var, True);
        $this->Carrier = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string TrackNumber = 4;</code>
     * @return string
     */
    public function getTrackNumber()
    {
        return $this->TrackNumber;
    }

    /**
     * Generated from protobuf field <code>string TrackNumber = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTrackNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->TrackNumber = $var;

        return $this;
    }

}

