<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shopex.proto

namespace Shopex\Luban\Sdf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>luban.Trade</code>
 */
class Trade extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Tid = 1;</code>
     */
    private $Tid = '';
    /**
     * Generated from protobuf field <code>string BuyerId = 2;</code>
     */
    private $BuyerId = '';
    /**
     * 卖家ID
     *
     * Generated from protobuf field <code>string SellerId = 3;</code>
     */
    private $SellerId = '';
    /**
     * Generated from protobuf field <code>.luban.TradeStatus Status = 4;</code>
     */
    private $Status = 0;
    /**
     * Generated from protobuf field <code>.luban.PayStatus PayStatus = 5;</code>
     */
    private $PayStatus = 0;
    /**
     * Generated from protobuf field <code>.luban.ShipStatus ShipStatus = 6;</code>
     */
    private $ShipStatus = 0;
    /**
     * Generated from protobuf field <code>repeated .luban.Order Order = 7;</code>
     */
    private $Order;
    /**
     * Generated from protobuf field <code>double ItemPrice = 8;</code>
     */
    private $ItemPrice = 0.0;
    /**
     * Generated from protobuf field <code>double PaidPrice = 9;</code>
     */
    private $PaidPrice = 0.0;
    /**
     * Generated from protobuf field <code>double PostFee = 10;</code>
     */
    private $PostFee = 0.0;
    /**
     * Generated from protobuf field <code>double DiscountFee = 11;</code>
     */
    private $DiscountFee = 0.0;
    /**
     * Generated from protobuf field <code>double AdjustFee = 12;</code>
     */
    private $AdjustFee = 0.0;
    /**
     * Generated from protobuf field <code>double FinalPrice = 13;</code>
     */
    private $FinalPrice = 0.0;
    /**
     * Generated from protobuf field <code>.luban.Address BuyerAddress = 14;</code>
     */
    private $BuyerAddress = null;
    /**
     * Generated from protobuf field <code>string DiscountToken = 15;</code>
     */
    private $DiscountToken = '';
    /**
     * Generated from protobuf field <code>string DiscountMemo = 16;</code>
     */
    private $DiscountMemo = '';
    /**
     * Generated from protobuf field <code>.luban.Invoice Invoice = 17;</code>
     */
    private $Invoice = null;
    /**
     * Generated from protobuf field <code>string BuyerMessage = 18;</code>
     */
    private $BuyerMessage = '';
    /**
     * Generated from protobuf field <code>int64 CreateTime = 19;</code>
     */
    private $CreateTime = 0;
    /**
     * Generated from protobuf field <code>int64 ModifiedTime = 20;</code>
     */
    private $ModifiedTime = 0;
    /**
     * Generated from protobuf field <code>int64 PayTime = 21;</code>
     */
    private $PayTime = 0;
    /**
     * Generated from protobuf field <code>int64 EndTime = 22;</code>
     */
    private $EndTime = 0;
    /**
     * Generated from protobuf field <code>repeated .luban.Meta Meta = 23;</code>
     */
    private $Meta;
    /**
     * Generated from protobuf field <code>repeated .luban.Payment Payment = 24;</code>
     */
    private $Payment;

    public function __construct() {
        \GPBMetadata\Shopex::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string Tid = 1;</code>
     * @return string
     */
    public function getTid()
    {
        return $this->Tid;
    }

    /**
     * Generated from protobuf field <code>string Tid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTid($var)
    {
        GPBUtil::checkString($var, True);
        $this->Tid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string BuyerId = 2;</code>
     * @return string
     */
    public function getBuyerId()
    {
        return $this->BuyerId;
    }

    /**
     * Generated from protobuf field <code>string BuyerId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBuyerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->BuyerId = $var;

        return $this;
    }

    /**
     * 卖家ID
     *
     * Generated from protobuf field <code>string SellerId = 3;</code>
     * @return string
     */
    public function getSellerId()
    {
        return $this->SellerId;
    }

    /**
     * 卖家ID
     *
     * Generated from protobuf field <code>string SellerId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSellerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->SellerId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.luban.TradeStatus Status = 4;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->Status;
    }

    /**
     * Generated from protobuf field <code>.luban.TradeStatus Status = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Shopex\Luban\Sdf\TradeStatus::class);
        $this->Status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.luban.PayStatus PayStatus = 5;</code>
     * @return int
     */
    public function getPayStatus()
    {
        return $this->PayStatus;
    }

    /**
     * Generated from protobuf field <code>.luban.PayStatus PayStatus = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setPayStatus($var)
    {
        GPBUtil::checkEnum($var, \Shopex\Luban\Sdf\PayStatus::class);
        $this->PayStatus = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.luban.ShipStatus ShipStatus = 6;</code>
     * @return int
     */
    public function getShipStatus()
    {
        return $this->ShipStatus;
    }

    /**
     * Generated from protobuf field <code>.luban.ShipStatus ShipStatus = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setShipStatus($var)
    {
        GPBUtil::checkEnum($var, \Shopex\Luban\Sdf\ShipStatus::class);
        $this->ShipStatus = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .luban.Order Order = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOrder()
    {
        return $this->Order;
    }

    /**
     * Generated from protobuf field <code>repeated .luban.Order Order = 7;</code>
     * @param \Shopex\Luban\Sdf\Order[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOrder($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Shopex\Luban\Sdf\Order::class);
        $this->Order = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double ItemPrice = 8;</code>
     * @return float
     */
    public function getItemPrice()
    {
        return $this->ItemPrice;
    }

    /**
     * Generated from protobuf field <code>double ItemPrice = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setItemPrice($var)
    {
        GPBUtil::checkDouble($var);
        $this->ItemPrice = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double PaidPrice = 9;</code>
     * @return float
     */
    public function getPaidPrice()
    {
        return $this->PaidPrice;
    }

    /**
     * Generated from protobuf field <code>double PaidPrice = 9;</code>
     * @param float $var
     * @return $this
     */
    public function setPaidPrice($var)
    {
        GPBUtil::checkDouble($var);
        $this->PaidPrice = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double PostFee = 10;</code>
     * @return float
     */
    public function getPostFee()
    {
        return $this->PostFee;
    }

    /**
     * Generated from protobuf field <code>double PostFee = 10;</code>
     * @param float $var
     * @return $this
     */
    public function setPostFee($var)
    {
        GPBUtil::checkDouble($var);
        $this->PostFee = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double DiscountFee = 11;</code>
     * @return float
     */
    public function getDiscountFee()
    {
        return $this->DiscountFee;
    }

    /**
     * Generated from protobuf field <code>double DiscountFee = 11;</code>
     * @param float $var
     * @return $this
     */
    public function setDiscountFee($var)
    {
        GPBUtil::checkDouble($var);
        $this->DiscountFee = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double AdjustFee = 12;</code>
     * @return float
     */
    public function getAdjustFee()
    {
        return $this->AdjustFee;
    }

    /**
     * Generated from protobuf field <code>double AdjustFee = 12;</code>
     * @param float $var
     * @return $this
     */
    public function setAdjustFee($var)
    {
        GPBUtil::checkDouble($var);
        $this->AdjustFee = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double FinalPrice = 13;</code>
     * @return float
     */
    public function getFinalPrice()
    {
        return $this->FinalPrice;
    }

    /**
     * Generated from protobuf field <code>double FinalPrice = 13;</code>
     * @param float $var
     * @return $this
     */
    public function setFinalPrice($var)
    {
        GPBUtil::checkDouble($var);
        $this->FinalPrice = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.luban.Address BuyerAddress = 14;</code>
     * @return \Shopex\Luban\Sdf\Address
     */
    public function getBuyerAddress()
    {
        return $this->BuyerAddress;
    }

    /**
     * Generated from protobuf field <code>.luban.Address BuyerAddress = 14;</code>
     * @param \Shopex\Luban\Sdf\Address $var
     * @return $this
     */
    public function setBuyerAddress($var)
    {
        GPBUtil::checkMessage($var, \Shopex\Luban\Sdf\Address::class);
        $this->BuyerAddress = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string DiscountToken = 15;</code>
     * @return string
     */
    public function getDiscountToken()
    {
        return $this->DiscountToken;
    }

    /**
     * Generated from protobuf field <code>string DiscountToken = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setDiscountToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->DiscountToken = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string DiscountMemo = 16;</code>
     * @return string
     */
    public function getDiscountMemo()
    {
        return $this->DiscountMemo;
    }

    /**
     * Generated from protobuf field <code>string DiscountMemo = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setDiscountMemo($var)
    {
        GPBUtil::checkString($var, True);
        $this->DiscountMemo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.luban.Invoice Invoice = 17;</code>
     * @return \Shopex\Luban\Sdf\Invoice
     */
    public function getInvoice()
    {
        return $this->Invoice;
    }

    /**
     * Generated from protobuf field <code>.luban.Invoice Invoice = 17;</code>
     * @param \Shopex\Luban\Sdf\Invoice $var
     * @return $this
     */
    public function setInvoice($var)
    {
        GPBUtil::checkMessage($var, \Shopex\Luban\Sdf\Invoice::class);
        $this->Invoice = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string BuyerMessage = 18;</code>
     * @return string
     */
    public function getBuyerMessage()
    {
        return $this->BuyerMessage;
    }

    /**
     * Generated from protobuf field <code>string BuyerMessage = 18;</code>
     * @param string $var
     * @return $this
     */
    public function setBuyerMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->BuyerMessage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 CreateTime = 19;</code>
     * @return int|string
     */
    public function getCreateTime()
    {
        return $this->CreateTime;
    }

    /**
     * Generated from protobuf field <code>int64 CreateTime = 19;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreateTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->CreateTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 ModifiedTime = 20;</code>
     * @return int|string
     */
    public function getModifiedTime()
    {
        return $this->ModifiedTime;
    }

    /**
     * Generated from protobuf field <code>int64 ModifiedTime = 20;</code>
     * @param int|string $var
     * @return $this
     */
    public function setModifiedTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->ModifiedTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 PayTime = 21;</code>
     * @return int|string
     */
    public function getPayTime()
    {
        return $this->PayTime;
    }

    /**
     * Generated from protobuf field <code>int64 PayTime = 21;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPayTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->PayTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 EndTime = 22;</code>
     * @return int|string
     */
    public function getEndTime()
    {
        return $this->EndTime;
    }

    /**
     * Generated from protobuf field <code>int64 EndTime = 22;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEndTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->EndTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .luban.Meta Meta = 23;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMeta()
    {
        return $this->Meta;
    }

    /**
     * Generated from protobuf field <code>repeated .luban.Meta Meta = 23;</code>
     * @param \Shopex\Luban\Sdf\Meta[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMeta($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Shopex\Luban\Sdf\Meta::class);
        $this->Meta = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .luban.Payment Payment = 24;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPayment()
    {
        return $this->Payment;
    }

    /**
     * Generated from protobuf field <code>repeated .luban.Payment Payment = 24;</code>
     * @param \Shopex\Luban\Sdf\Payment[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPayment($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Shopex\Luban\Sdf\Payment::class);
        $this->Payment = $arr;

        return $this;
    }

}

