<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: svc_dealer.proto

namespace Shopex\Luban\Sdf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>luban.TradeAfterSaleRequest</code>
 */
class TradeAfterSaleRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Tid = 1;</code>
     */
    private $Tid = '';
    /**
     * Generated from protobuf field <code>string Reason = 2;</code>
     */
    private $Reason = '';
    /**
     * Generated from protobuf field <code>string Mobile = 3;</code>
     */
    private $Mobile = '';
    /**
     * Generated from protobuf field <code>string Status = 4;</code>
     */
    private $Status = '';
    /**
     * Generated from protobuf field <code>int64 ItemId = 5;</code>
     */
    private $ItemId = 0;
    /**
     * Generated from protobuf field <code>int64 SkuId = 6;</code>
     */
    private $SkuId = 0;
    /**
     * Generated from protobuf field <code>int64 Num = 7;</code>
     */
    private $Num = 0;

    public function __construct() {
        \GPBMetadata\SvcDealer::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string Tid = 1;</code>
     * @return string
     */
    public function getTid()
    {
        return $this->Tid;
    }

    /**
     * Generated from protobuf field <code>string Tid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTid($var)
    {
        GPBUtil::checkString($var, True);
        $this->Tid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Reason = 2;</code>
     * @return string
     */
    public function getReason()
    {
        return $this->Reason;
    }

    /**
     * Generated from protobuf field <code>string Reason = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setReason($var)
    {
        GPBUtil::checkString($var, True);
        $this->Reason = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Mobile = 3;</code>
     * @return string
     */
    public function getMobile()
    {
        return $this->Mobile;
    }

    /**
     * Generated from protobuf field <code>string Mobile = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->Mobile = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Status = 4;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->Status;
    }

    /**
     * Generated from protobuf field <code>string Status = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->Status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 ItemId = 5;</code>
     * @return int|string
     */
    public function getItemId()
    {
        return $this->ItemId;
    }

    /**
     * Generated from protobuf field <code>int64 ItemId = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setItemId($var)
    {
        GPBUtil::checkInt64($var);
        $this->ItemId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 SkuId = 6;</code>
     * @return int|string
     */
    public function getSkuId()
    {
        return $this->SkuId;
    }

    /**
     * Generated from protobuf field <code>int64 SkuId = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSkuId($var)
    {
        GPBUtil::checkInt64($var);
        $this->SkuId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 Num = 7;</code>
     * @return int|string
     */
    public function getNum()
    {
        return $this->Num;
    }

    /**
     * Generated from protobuf field <code>int64 Num = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNum($var)
    {
        GPBUtil::checkInt64($var);
        $this->Num = $var;

        return $this;
    }

}

