<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: svc_trigger.proto

namespace Shopex\Luban\Sdf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>luban.TriggerUpdateRequest</code>
 */
class TriggerUpdateRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 Id = 1;</code>
     */
    private $Id = 0;
    /**
     * Generated from protobuf field <code>.luban.Trigger Trigger = 2;</code>
     */
    private $Trigger = null;

    public function __construct() {
        \GPBMetadata\SvcTrigger::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int64 Id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->Id;
    }

    /**
     * Generated from protobuf field <code>int64 Id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->Id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.luban.Trigger Trigger = 2;</code>
     * @return \Shopex\Luban\Sdf\Trigger
     */
    public function getTrigger()
    {
        return $this->Trigger;
    }

    /**
     * Generated from protobuf field <code>.luban.Trigger Trigger = 2;</code>
     * @param \Shopex\Luban\Sdf\Trigger $var
     * @return $this
     */
    public function setTrigger($var)
    {
        GPBUtil::checkMessage($var, \Shopex\Luban\Sdf\Trigger::class);
        $this->Trigger = $var;

        return $this;
    }

}

