<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: svc_trigger.proto

namespace Shopex\Luban\Sdf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>luban.TriggerUpdateResponse</code>
 */
class TriggerUpdateResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Msg = 1;</code>
     */
    private $Msg = '';
    /**
     * Generated from protobuf field <code>bool Result = 2;</code>
     */
    private $Result = false;

    public function __construct() {
        \GPBMetadata\SvcTrigger::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string Msg = 1;</code>
     * @return string
     */
    public function getMsg()
    {
        return $this->Msg;
    }

    /**
     * Generated from protobuf field <code>string Msg = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->Msg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool Result = 2;</code>
     * @return bool
     */
    public function getResult()
    {
        return $this->Result;
    }

    /**
     * Generated from protobuf field <code>bool Result = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkBool($var);
        $this->Result = $var;

        return $this;
    }

}

