<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: svc_trigger.proto

namespace Shopex\Luban\Sdf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>luban.TriggerListResponse</code>
 */
class TriggerListResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .luban.Trigger Data = 1;</code>
     */
    private $Data;
    /**
     * Generated from protobuf field <code>int64 Count = 2;</code>
     */
    private $Count = 0;

    public function __construct() {
        \GPBMetadata\SvcTrigger::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .luban.Trigger Data = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getData()
    {
        return $this->Data;
    }

    /**
     * Generated from protobuf field <code>repeated .luban.Trigger Data = 1;</code>
     * @param \Shopex\Luban\Sdf\Trigger[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setData($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Shopex\Luban\Sdf\Trigger::class);
        $this->Data = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 Count = 2;</code>
     * @return int|string
     */
    public function getCount()
    {
        return $this->Count;
    }

    /**
     * Generated from protobuf field <code>int64 Count = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->Count = $var;

        return $this;
    }

}

