<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trigger.proto

namespace Shopex\Luban\Sdf;

/**
 * Protobuf enum <code>Luban\Trigger\ModeType</code>
 */
class Trigger_ModeType
{
    /**
     *未锁定
     *
     * Generated from protobuf enum <code>NORMAL = 0;</code>
     */
    const NORMAL = 0;
    /**
     *未锁定
     *
     * Generated from protobuf enum <code>LUA = 1;</code>
     */
    const LUA = 1;
}

