<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trigger.proto

namespace Shopex\Luban\Sdf;

/**
 * Protobuf enum <code>Luban\Trigger\Lock</code>
 */
class Trigger_Lock
{
    /**
     *未锁定
     *
     * Generated from protobuf enum <code>UNLOCK = 0;</code>
     */
    const UNLOCK = 0;
    /**
     *锁定
     *
     * Generated from protobuf enum <code>LOCK = 1;</code>
     */
    const LOCK = 1;
}

