<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trigger.proto

namespace Shopex\Luban\Sdf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>luban.Trigger</code>
 */
class Trigger extends \Google\Protobuf\Internal\Message
{
    /**
     *事件名称
     *
     * Generated from protobuf field <code>string Event = 1;</code>
     */
    private $Event = '';
    /**
     *lua模式
     *
     * Generated from protobuf field <code>.luban.Trigger.ModeType Mode = 2;</code>
     */
    private $Mode = 0;
    /**
     *FilterLua表达式
     *
     * Generated from protobuf field <code>string Filters = 3;</code>
     */
    private $Filters = '';
    /**
     *FilterLua代码
     *
     * Generated from protobuf field <code>string FilterLua = 4;</code>
     */
    private $FilterLua = '';
    /**
     *动作
     *
     * Generated from protobuf field <code>string Actions = 5;</code>
     */
    private $Actions = '';
    /**
     *开始时间
     *
     * Generated from protobuf field <code>int64 BeginTime = 6;</code>
     */
    private $BeginTime = 0;
    /**
     *结束时间
     *
     * Generated from protobuf field <code>int64 EndTime = 7;</code>
     */
    private $EndTime = 0;
    /**
     *租户ID
     *
     * Generated from protobuf field <code>int64 SiteId = 8;</code>
     */
    private $SiteId = 0;
    /**
     *排序
     *
     * Generated from protobuf field <code>int64 OrderSort = 9;</code>
     */
    private $OrderSort = 0;
    /**
     *描述
     *
     * Generated from protobuf field <code>string Description = 10;</code>
     */
    private $Description = '';
    /**
     *是否锁定
     *
     * Generated from protobuf field <code>.luban.Trigger.Lock IsLock = 11;</code>
     */
    private $IsLock = 0;

    public function __construct() {
        \GPBMetadata\Trigger::initOnce();
        parent::__construct();
    }

    /**
     *事件名称
     *
     * Generated from protobuf field <code>string Event = 1;</code>
     * @return string
     */
    public function getEvent()
    {
        return $this->Event;
    }

    /**
     *事件名称
     *
     * Generated from protobuf field <code>string Event = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setEvent($var)
    {
        GPBUtil::checkString($var, True);
        $this->Event = $var;

        return $this;
    }

    /**
     *lua模式
     *
     * Generated from protobuf field <code>.luban.Trigger.ModeType Mode = 2;</code>
     * @return int
     */
    public function getMode()
    {
        return $this->Mode;
    }

    /**
     *lua模式
     *
     * Generated from protobuf field <code>.luban.Trigger.ModeType Mode = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMode($var)
    {
        GPBUtil::checkEnum($var, \Shopex\Luban\Sdf\Trigger_ModeType::class);
        $this->Mode = $var;

        return $this;
    }

    /**
     *FilterLua表达式
     *
     * Generated from protobuf field <code>string Filters = 3;</code>
     * @return string
     */
    public function getFilters()
    {
        return $this->Filters;
    }

    /**
     *FilterLua表达式
     *
     * Generated from protobuf field <code>string Filters = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setFilters($var)
    {
        GPBUtil::checkString($var, True);
        $this->Filters = $var;

        return $this;
    }

    /**
     *FilterLua代码
     *
     * Generated from protobuf field <code>string FilterLua = 4;</code>
     * @return string
     */
    public function getFilterLua()
    {
        return $this->FilterLua;
    }

    /**
     *FilterLua代码
     *
     * Generated from protobuf field <code>string FilterLua = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setFilterLua($var)
    {
        GPBUtil::checkString($var, True);
        $this->FilterLua = $var;

        return $this;
    }

    /**
     *动作
     *
     * Generated from protobuf field <code>string Actions = 5;</code>
     * @return string
     */
    public function getActions()
    {
        return $this->Actions;
    }

    /**
     *动作
     *
     * Generated from protobuf field <code>string Actions = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setActions($var)
    {
        GPBUtil::checkString($var, True);
        $this->Actions = $var;

        return $this;
    }

    /**
     *开始时间
     *
     * Generated from protobuf field <code>int64 BeginTime = 6;</code>
     * @return int|string
     */
    public function getBeginTime()
    {
        return $this->BeginTime;
    }

    /**
     *开始时间
     *
     * Generated from protobuf field <code>int64 BeginTime = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBeginTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->BeginTime = $var;

        return $this;
    }

    /**
     *结束时间
     *
     * Generated from protobuf field <code>int64 EndTime = 7;</code>
     * @return int|string
     */
    public function getEndTime()
    {
        return $this->EndTime;
    }

    /**
     *结束时间
     *
     * Generated from protobuf field <code>int64 EndTime = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEndTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->EndTime = $var;

        return $this;
    }

    /**
     *租户ID
     *
     * Generated from protobuf field <code>int64 SiteId = 8;</code>
     * @return int|string
     */
    public function getSiteId()
    {
        return $this->SiteId;
    }

    /**
     *租户ID
     *
     * Generated from protobuf field <code>int64 SiteId = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSiteId($var)
    {
        GPBUtil::checkInt64($var);
        $this->SiteId = $var;

        return $this;
    }

    /**
     *排序
     *
     * Generated from protobuf field <code>int64 OrderSort = 9;</code>
     * @return int|string
     */
    public function getOrderSort()
    {
        return $this->OrderSort;
    }

    /**
     *排序
     *
     * Generated from protobuf field <code>int64 OrderSort = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOrderSort($var)
    {
        GPBUtil::checkInt64($var);
        $this->OrderSort = $var;

        return $this;
    }

    /**
     *描述
     *
     * Generated from protobuf field <code>string Description = 10;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->Description;
    }

    /**
     *描述
     *
     * Generated from protobuf field <code>string Description = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->Description = $var;

        return $this;
    }

    /**
     *是否锁定
     *
     * Generated from protobuf field <code>.luban.Trigger.Lock IsLock = 11;</code>
     * @return int
     */
    public function getIsLock()
    {
        return $this->IsLock;
    }

    /**
     *是否锁定
     *
     * Generated from protobuf field <code>.luban.Trigger.Lock IsLock = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setIsLock($var)
    {
        GPBUtil::checkEnum($var, \Shopex\Luban\Sdf\Trigger_Lock::class);
        $this->IsLock = $var;

        return $this;
    }

}

